# App
server:
    port: 8080
    
# Spring
spring:
  devtools:
    restart:
      enabled: true
          
  # DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    schema: classpath:/db/schema-postgresql.sql
    data: classpath:/db/data-postgresql.sql
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456
#    platform: postgresql
    initialization-mode: always
    continue-on-error: false

# Mybatis Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.pf.myframework.core.entity
  typeEnumsPackage: com.pf.myframework.core.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      # 字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断"), NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      # 驼峰下划线转换
      column-underline: true
      # 数据库大写下划线转换
#      capital-mode: true
      # 逻辑删除配置
      logic-delete-value: 1 #默认值1
      logic-not-delete-value: 0 #默认值0
#      db-type: POSTGRE_SQL
    # 刷新mapper 调试神器
    refresh: true
  # Mybatis 的原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    jdbc-type-for-null: 'null'

# Logger
logging:
  level:
    com.pf.myframework: debug
